name: Flutter Flashcard Web Deploy
on: 
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web --release
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
          commit_message: 'Publish to gh-pages'
      
      
      # - run: flutter build web --release --base-href /flutter_web/
      # - run: git config user.name github-actions
      # - run: git config user.email github-actions@github.com
      # - run: git --work-tree build/web add --all
      # - run: git commit -m "Automatic deployment by github-actions"
      # - run: git push origin HEAD:gh-pages --force
